import { Product } from '@/types/schema';

const now = new Date().toISOString();
export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Ração Super Premium Aurora Holistic Nutrition Cães Adultos 12kg',
    slug: 'racao-aurora-super-premium-12kg',
    description: 'Fórmula holística com carne bovina alimentada a pasto e batata doce, rica em ômega 3 e 6 para pelagem brilhante e suporte articular.',
    short_description: 'Nutrição holística e ingredientes selecionados',
    price: 189.90,
    compare_at_price: 229.90,
    stock: 45,
    category_id: '1',
    brand: 'Aurora Pet Co.',
    image_urls: ['/images/prod-dog-food.jpg'],
    animal_types: ['dog'],
    featured: true,
    active: true,
    tags: ['racao', 'super-premium', 'caes'],
    created_at: now,
    updated_at: now,
  },
  {
    id: '2',
    name: 'Caminha Donut Faux-Fur Nuvem Ultra Macia Bege',
    slug: 'caminha-donut-nuvem-bege',
    description: 'Cama anatômica relaxante antiestresse com bordas elevadas que proporcionam segurança e suporte ortopédico para a cabeça e coluna.',
    short_description: 'Máximo conforto térmico e alívio do estresse',
    price: 149.90,
    compare_at_price: 189.90,
    stock: 30,
    category_id: '5',
    brand: 'CozyPaws',
    image_urls: ['/images/prod-pet-bed.jpg'],
    animal_types: ['dog', 'cat'],
    featured: true,
    active: true,
    tags: ['caminhas', 'conforto', 'acessorios'],
    created_at: now,
    updated_at: now,
  },
  {
    id: '3',
    name: 'Brinquedo Pelúcia Raposinha Plush Squeaky com Corda',
    slug: 'brinquedo-pelucia-raposinha-corda',
    description: 'Brinquedo interativo de textura macia com apito interno sonoro e nó de corda resistente que auxilia na limpeza dental dos pets.',
    short_description: 'Diversão e estímulo mental para seu amigo',
    price: 49.90,
    compare_at_price: 69.90,
    stock: 60,
    category_id: '3',
    brand: 'PawPlay',
    image_urls: ['/images/prod-pet-toy.jpg'],
    animal_types: ['dog', 'cat'],
    featured: true,
    active: true,
    tags: ['brinquedos', 'mordedor', 'pelucia'],
    created_at: now,
    updated_at: now,
  },
  {
    id: '4',
    name: 'Kit Banho & Tosa: Shampoo Ultra-Gentle 473ml + Escova Bambu Natural',
    slug: 'kit-banho-shampoo-escova-bambu',
    description: 'Fórmula vegana livre de sulfatos e parabenos com extratos botânicos. Acompanha escova de cerdas naturais de bambu que desembaraça sem machucar.',
    short_description: 'Cuidado dermatológico e brilho da pelagem',
    price: 89.90,
    compare_at_price: 119.90,
    stock: 35,
    category_id: '6',
    brand: 'Fur & Bloom',
    image_urls: ['/images/prod-grooming.jpg'],
    animal_types: ['dog', 'cat'],
    featured: true,
    active: true,
    tags: ['higiene', 'shampoo', 'banho'],
    created_at: now,
    updated_at: now,
  },
];
