import { Product } from '@/types/schema';

const now = new Date().toISOString();
export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Racao Pedigree Adulto',
    slug: 'racao-pedigree-adulto',
    description: 'Racao premium para caes adultos',
    short_description: 'Racao Pedigree',
    price: 129.90,
    compare_at_price: 149.90,
    stock: 50,
    category_id: '1',
    brand: 'Pedigree',
    image_urls: [],
    animal_types: ['dog'],
    featured: true,
    active: true,
    tags: ['racao'],
    created_at: now,
    updated_at: now,
  },
  {
    id: '2',
    name: 'Racao Whiskas Adulto',
    slug: 'racao-whiskas-adulto',
    description: 'Racao para gatos adultos',
    short_description: 'Racao Whiskas',
    price: 49.90,
    compare_at_price: null,
    stock: 100,
    category_id: '2',
    brand: 'Whiskas',
    image_urls: [],
    animal_types: ['cat'],
    featured: true,
    active: true,
    tags: ['racao'],
    created_at: now,
    updated_at: now,
  },
  {
    id: '3',
    name: 'Coleira Luxo',
    slug: 'coleira-luxo',
    description: 'Coleira premium',
    short_description: 'Coleira Luxo',
    price: 39.90,
    compare_at_price: null,
    stock: 30,
    category_id: '3',
    brand: 'PetPr1me',
    image_urls: [],
    animal_types: ['dog'],
    featured: true,
    active: true,
    tags: ['acessorio'],
    created_at: now,
    updated_at: now,
  },
  {
    id: '4',
    name: 'Racao GranNature Small Breed',
    slug: 'racao-grannature-small-breed',
    description: 'Racao premium para caes pequenos',
    short_description: 'GranNature',
    price: 199.90,
    compare_at_price: 219.90,
    stock: 25,
    category_id: '1',
    brand: 'GranNature',
    image_urls: [],
    animal_types: ['dog'],
    featured: true,
    active: true,
    tags: ['racao'],
    created_at: now,
    updated_at: now,
  },
];
